import 'server-only';
import { Client } from '@notionhq/client';
import { cache } from 'react';
import { INotionProperties, NotionPost, IRawNotionPost, BlockObjectResponse } from '@hooneylog/shared-types';
import { NotionToMarkdown } from 'notion-to-md';

const notion = new Client({
  auth: process.env.NOTION_API_KEY,
});

const n2m = new NotionToMarkdown({ notionClient: notion });

// Add custom transformer for Callouts
n2m.setCustomTransformer('callout', async (block) => {
  if (!('type' in block) || block.type !== 'callout') return '';
  const { callout } = block;
  const icon = callout.icon?.type === 'emoji' ? callout.icon.emoji : '💡';
  const text = callout.rich_text.map((t) => t.plain_text).join('');
  
  return `<div class="notion-callout">
    <div class="notion-callout-icon">${icon}</div>
    <div class="notion-callout-content">${text}</div>
  </div>`;
});

const databaseId = process.env.NOTION_DATABASE_ID ?? '';

// Simple in-memory queue to strictly serialize Notion API calls
let queue = Promise.resolve();

// Helper for retrying Notion API calls to handle transient network errors and rate limits (429)
async function withRetry<T>(fn: () => Promise<T>, retries = 5, delay = 2000): Promise<T> {
  const execute = async (currentRetries: number, currentDelay: number): Promise<T> => {
    try {
      return await fn();
    } catch (error: unknown) {
      if (currentRetries > 0) {
        const isRateLimited = typeof error === 'object' && error !== null && 
          (('status' in error && error.status === 429) || ('code' in error && error.code === 'rate_limited'));
          
        if (isRateLimited) {
          console.warn(`Notion API rate limited (429). Retrying in ${currentDelay}ms... (${currentRetries} retries left)`);
        } else {
          console.warn(`Notion API call failed, retrying in ${currentDelay}ms... (${currentRetries} retries left)`);
        }
        
        const jitter = Math.floor(Math.random() * 1000);
        await new Promise(resolve => setTimeout(resolve, currentDelay + jitter));
        
        return execute(currentRetries - 1, currentDelay * 2);
      }
      throw error;
    }
  };

  // Add the execution to the global queue to prevent concurrent requests
  const result = new Promise<T>((resolve, reject) => {
    queue = queue.then(async () => {
      // Small pause between all requests to keep average rate low
      await new Promise(r => setTimeout(r, 400)); 
      try {
        const res = await execute(retries, delay);
        resolve(res);
      } catch (err) {
        reject(err);
      }
    });
  });

  return result;
}

/**
 * Fixes markdown strings generated by notion-to-md.
 * Recursively unescapes over-escaped markers and cleans up redundant markers.
 */
function fixMarkdown(md: string): string {
  if (!md) return md;

  // 1. Initial cleanup of redundant markers and unescaping
  let result = md
    .replace(/\*\*\*\*/g, '')
    .replace(/~~~~/g, '')
    .replace(/\*\* \*\*/g, ' ')
    .replace(/__ __/g, ' ');

  // 2. Unescape markers recursively (handles double/triple escaping)
  let previous;
  do {
    previous = result;
    result = result.replace(/\\([*|_~`[\]()#+!.-])/g, '$1');  } while (result !== previous);

  // 3. Force bold markers into HTML strong tags
  // This bypasses markdown parser limitations when bold is adjacent to other text
  result = result.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');

  // 4. Final cleanup of adjacent markers that might have been revealed
  result = result.replace(/\*\*\*\*/g, '');

  // 5. Fix Notion's "1)" list style to standard "1."
  result = result.replace(/^(\s*)(\d+)\)\s/gm, '$1$2. ');

  return result;
}

export const getNotionPageMarkdown = cache(async (pageId: string) => {
  const mdblocks = await withRetry(() => n2m.pageToMarkdown(pageId));
  const mdString = n2m.toMarkdownString(mdblocks);
  
  if (mdString.parent) {
    mdString.parent = fixMarkdown(mdString.parent);
  }

  return mdString;
});

class NotionBlockMapper {
  private readonly properties: INotionProperties;

  constructor(properties: INotionProperties) {
    this.properties = properties;
  }

  get title() {
    return this.properties.이름?.title?.[0]?.plain_text || '';
  }

  get createdAt() {
    return this.properties.created_date?.created_time || '';
  }

  get category() {
    return this.properties.category?.multi_select?.[0]?.name || '';
  }

  get tags() {
    return this.properties.tag?.multi_select || [];
  }

  get description() {
    return this.properties.description?.rich_text?.[0]?.plain_text || '';
  }
}

export const getAllPosts = cache(async (): Promise<NotionPost[]> => {
  if (!databaseId) return [];

  const response = await withRetry(() => notion.databases.query({
    database_id: databaseId,
    filter: {
      property: 'status',
      select: {
        equals: 'published',
      },
    },
    sorts: [
      {
        timestamp: 'created_time',
        direction: 'descending',
      },
    ],
  }));

  const rawPosts = response.results as unknown as IRawNotionPost[];

  return rawPosts.map(({ id, properties }) => {
    const block = new NotionBlockMapper(properties);
    return {
      id,
      title: block.title,
      tags: block.tags,
      createdAt: block.createdAt,
      category: block.category,
      description: block.description,
    };
  });
});

export const getPostById = cache(async (postId: string): Promise<NotionPost | undefined> => {
  const posts = await getAllPosts();
  return posts.find(({ id }) => id === postId);
});

export const getBlocksById = cache(async (id: string): Promise<BlockObjectResponse[]> => {
  if (!id) return [];
  const blocks: BlockObjectResponse[] = [];
  let cursor: string | undefined = undefined;

  while (true) {
    const { results, next_cursor } = await withRetry(() => notion.blocks.children.list({
      block_id: id,
      start_cursor: cursor,
    }));
    
    // Filter out partial blocks to ensure we have full BlockObjectResponse
    const fullBlocks = results.filter((block): block is BlockObjectResponse => 'type' in block);
    blocks.push(...fullBlocks);
    
    if (!next_cursor) {
      break;
    }

    cursor = next_cursor;
  }

  return blocks;
});
